bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Andries van Tonder
  description: This pipeline maps bacterial sequence data to a reference
  force: true
  is_nfcore: true
  name: mapBAC
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0dev
update: null
