contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mapbac channel"
    url: https://nfcore.slack.com/channels/mapbac
    about: Discussion about the nf-core/mapbac pipeline
